tasks/config/routes.rb
Rails.application.routes.draw do
  root :to => 'tasks#index'

  resources :tasks
end

tasks/app/models/account.rb
class Account < ApplicationRecord
end

tasks/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

tasks/app/models/task.rb
class Task < ApplicationRecord
end

tasks/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

tasks/app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[ show edit update destroy ]

  # GET /tasks or /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1 or /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks or /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: "Task was successfully created." }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: "Task was successfully updated." }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: "Task was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task).permit(:description, :status)
    end
end

tasks/app/helpers/application_helper.rb
module ApplicationHelper
end

tasks/app/helpers/tasks_helper.rb
module TasksHelper
end

tasks/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tasks</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

tasks/app/views/tasks/_form.html.haml
= form_for(@task) do |f|
  - if @task.errors.any?
    #error_explanation
      %h2
        = pluralize(@task.errors.count, "error")
        prohibited this task from being saved:
      %ul
        - @task.errors.full_messages.each do |message|
          %li= message

  .form-group
    = f.text_field :description
    -# = f.select :status, options_for_select(status_options)
  .actions
    = f.submit

tasks/app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

tasks/app/views/tasks/index.html.haml
%p#notice= notice
%h1 Listing Tasks
%table.table
  %thead
    %tr
      %th Description
      %th Status
      %th{:colspan => "3"}
  %tbody
    - @tasks.each do |task|
      %tr
        %td= task.description
        %td= task.status
        %td= link_to 'Show', task
        %td= link_to 'Edit', edit_task_path(task)
        %td= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Task', new_task_path

tasks/app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path %>

tasks/app/views/tasks/show.html.haml
%p#notice= notice
%label Description
= @task.description

%label Status
= @task.status
= link_to 'Edit', edit_task_path(@task)
= link_to 'Back', tasks_path